# Generated by Django 5.1.2 on 2024-10-23 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiondata',
            old_name='eye_aspect_ratio_avg',
            new_name='avg_eye_aspect_ratio',
        ),
        migrations.RenameField(
            model_name='sessiondata',
            old_name='blink_count',
            new_name='total_blinks',
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sessiondata',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='session_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='session_id',
            field=models.CharField(default='default_session', max_length=100),
        ),
        migrations.AddField(
            model_name='sessiondata',
            name='session_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
