# Generated by Django 5.1.2 on 2024-10-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eyemetrics',
            old_name='eye_aspect_ratio_avg',
            new_name='eye_aspect_ratio',
        ),
        migrations.AddField(
            model_name='eyemetrics',
            name='frame_id',
            field=models.IntegerField(default=0),
        ),
    ]
